#non_tokenizing_transformer.n_heads: [2,8]
#non_tokenizing_transformer.n_layers: [2,4,8]
#MultifactorSchedule.constant: [0.0001, 0.001, 0.01]
#non_tokenizing_transformer.dropout: [0.1, 0.2]
#
# non_tokenizing_transformer.n_heads: [1,2]
# non_tokenizing_transformer.n_layers: [1,2]
# MultifactorSchedule.constant: [0.01, 0.1]
# non_tokenizing_transformer.d_model: [512, 1024]
# non_tokenizing_transformer.d_ff: [1024, 2048]
#MultifactorSchedule.constant: [0.1, 1, 10, 100, 1000]
# non_tokenizing_transformer.n_heads: [1,2]
# non_tokenizing_transformer.n_layers: [1,2]
# MultifactorSchedule.constant: [0.01, 0.1]
# non_tokenizing_transformer.d_model: [512, 1024]
# non_tokenizing_transformer.d_ff: [1024, 2048]
